// <auto-generated />
using APIEducagame.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APIEducagame.Migrations
{
    [DbContext(typeof(AppContexto))]
    [Migration("20191006183146_Ponto")]
    partial class Ponto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("APIEducagame.Model.Ponto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("campo1");

                    b.Property<int>("campo2");

                    b.Property<int>("campo3");

                    b.Property<int>("campo4");

                    b.Property<int>("campo5");

                    b.Property<int>("campo6");

                    b.HasKey("Id");

                    b.ToTable("Ponto");
                });
#pragma warning restore 612, 618
        }
    }
}
